### ISSUE TITLE
Working with submodular 

### ISSUE THREAD

**Issue by amaury-hanser** [aptly-io/grav-plugin-googlemaps#7]
Hello, 

I would like to suggest a new feature if it's possible:
Being able to declare the map in a modular page and have a submodular page for each marker.
I.e.
The main page would have this frontmatter:
```
googlemaps:
    track_01:
        center: 51.009314, 4.061254
        zoom: 12
        markers:
```
While each subpages would have a frontmatter like this:
```
            - location: 51.009358, 4.061578
              title: The local church
              zIndex: 1
              timeout: 1000
              info: <strong>The local church</strong>.<br/>Cleaned up in recent years!
```

What do you think about it ?
